# Generated by Django 5.2.17 on 2026-10-07 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(null=True)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('sends', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
