from pathlib import Path
from uuid import uuid4

import cloudinary
import cloudinary.uploader
from django.conf import settings
from django.core.files.storage import FileSystemStorage, Storage
from django.utils.deconstruct import deconstructible


@deconstructible
class ProductImageStorage(Storage):
    """New uploads use Cloudinary; existing local image paths remain readable."""
    prefix = 'cloudinary/'

    def _save(self, name, content):
        public_id = 'cocoa_bliss/products/' + uuid4().hex
        try:
            result = cloudinary.uploader.upload(
                content, public_id=public_id, resource_type='image',
                overwrite=False, timeout=20,
            )
        except Exception:
            raise OSError('Cloudinary upload failed. Check the account configuration.') from None
        return self.prefix + result['public_id'] + '.' + result['format']

    def exists(self, name):
        # New uploads have unique public IDs generated by _save.
        return False

    def url(self, name):
        if name.startswith(self.prefix):
            return cloudinary.CloudinaryImage(name[len(self.prefix):]).build_url(secure=True)
        return FileSystemStorage().url(name)

    def _open(self, name, mode='rb'):
        if not name.startswith(self.prefix):
            return FileSystemStorage().open(name, mode)
        raise NotImplementedError('Remote images are served through their Cloudinary URL.')

    def delete(self, name):
        if name.startswith(self.prefix):
            public_id = name[len(self.prefix):].rsplit('.', 1)[0]
            cloudinary.uploader.destroy(public_id, resource_type='image', timeout=20)
        else:
            FileSystemStorage().delete(name)
