# Generated by Django 5.2.17 on 2026-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units available to sell. Pending orders already reserve their units.'),
        ),
    ]
