# Generated by Django 5.2.17 on 2026-10-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='inr', max_length=3),
        ),
    ]
