# Generated by Django 5.2.17 on 2026-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_country_alter_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
